services:
  web:
    environment:
#      - MINIO_KEY=F5OqGvkU1mZCzfUr
#      - MINIO_SECRET=C5BImJ4b8GKXbLfQ2QzScmN57hTYIGhD
    build:
      context: .
    container_name: app
    restart: always
    ports:
      - '8000:8000'
    networks:
      - main_network
    depends_on:
      - db
      - selenium
      - minio
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: links
    ports:
      - '5432:5432'
    volumes:
      - pg_storage:/var/lib/postgresql/data
    networks:
      - main_network
  minio:
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_storage:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=images
    networks:
      - main_network
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    ports:
      - '4444:4444'
    networks:
      - main_network
    depends_on:
      - minio
networks:
  main_network:
    driver: bridge
volumes:
    pg_storage:
      driver: local
    minio_storage:
      driver: local
